### ISSUE TITLE
Autocomplete support for instantiated classes

### ISSUE THREAD

**Issue by stnvh** [Gert-dev/php-integrator-autocomplete-plus#17]
Not sure if this should be against the base, so forgive me if so!
It would be really cool to have autocomplete for instantiated classes e.g

```php
<?php

class Foo {
	public function bar() {}
}

$myClass = new Foo();
```
so the suggestions for non-static functions would then be displayed when referencing `$myClass`

**Comment by Gert-dev** [comment]
Hello

This is actually already supported. It may not be working because your file may not be indexing properly. Are you using proper namespacing and autoloading (as per the PSR standards)?

**Comment by stnvh** [comment]
I should of mentioned; the classnames I'm referencing aren't included directly within the file itself - I'm using a framework which has a non-standard autoloader.
I assumed all indexed classes were referenceable from within files which don't directly include them (`use` etc.), as this is the default framework behaviour, apologies for the mix-up. 
Would an option to allow autocomplete for *all* indexed classes, despite not being directly included within the current file, be a way around this? Currently - in my case - class suggestions *are* shown in every file, but when instantiated, nothing is suggested! 
A very handy plugin however, makes atom feel like an IDE! :+1:

**Comment by Gert-dev** [comment]
Thanks for your kind words. Autocompletion should in fact already list all available classes in your codebase (and not just the ones explicitly included). The reason they may not be showing up is because they need Composer's (or a custom) class map that lists them. This file can be configured in the settings screen and is usually called `autoload_classmap.php` if you're using Composer. If you're not using Composer, you can always write up a classmap of your own or look for a tool that can generate a list of classes with their respective files for your custom framework. An example `autoload_classmap.php` looks like this:

```php
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'GlobalClass' => $baseDir . '/src/include.php',
    'GlobalClass2' => $baseDir . '/src/include.php',
    'TestNamespace\\AnotherClass' => $baseDir . '/src/TestNamespace/AnotherClass.php',
    'TestNamespace\\Bar\\BarClass' => $baseDir . '/src/TestNamespace/Bar/BarClass.php'
);
```

**Comment by Gert-dev** [comment]
Just wanted to mention that 0.4.0 was just released and does not require an autoloader, autoloading classmap nor Composer anymore, so it may yield better results for your use case, even if it's not officially supported. If you have any more questions, feel free to let me know.
