### ISSUE TITLE
Oneline phpdoc doesn't autocomplete

### ISSUE THREAD

**Issue by squio** [Gert-dev/php-integrator-autocomplete-plus#61]
Hi,

When editing a one-line phpdoc annotation autocompletion doesn't work.

**Example**:

    /**
    * @var int $status model status encoded
    */

While typing the option `@var` is suggested once the characters `@va` are entered:

<img width="207" alt="screen shot 2016-08-04 at 23 12 01" src="https://cloud.githubusercontent.com/assets/169410/17418492/1c255948-5a99-11e6-99a7-cf833750d296.png">

Syntax coloring is correct:

<img width="319" alt="screen shot 2016-08-04 at 23 13 01" src="https://cloud.githubusercontent.com/assets/169410/17418519/3f5aac24-5a99-11e6-91e8-622f144d0999.png">

**Oneliner**: 

    /** @var int $status model status encoded */

The sequence `@var` is NOT suggested:

<img width="106" alt="screen shot 2016-08-04 at 23 12 29" src="https://cloud.githubusercontent.com/assets/169410/17418526/46c4f564-5a99-11e6-8a73-f303a823ba61.png">

and syntax coloring is NOT applied:

<img width="345" alt="screen shot 2016-08-04 at 23 13 09" src="https://cloud.githubusercontent.com/assets/169410/17418532/4c3cb2b6-5a99-11e6-8ef4-008757ae9211.png">

Platform: Atom 1.9.2 
OS: OS-X Mavericks

**Comment by Gert-dev** [comment]
The autocompletion not triggering is definitely a bug. However, the syntax highlighting is not handled by this package, but by Atom's language-php [1]. You might want to report it there instead.

[1] https://github.com/atom/language-php

**Comment by Gert-dev** [comment]
It turns out this is not really a bug in this package. The regular expression used internally correctly matches, but the syntax highlighting is also checked to see if the cursor is currently inside a docblock. Apparently, however, `language-php` does not mark a single line docblock as a docblock [1]. In other words, this issue will be resolved automatically as soon as that one is resolved.

[1] https://github.com/atom/language-php/issues/135
