### ISSUE TITLE
Autocomplete suggestions are delayed

### ISSUE THREAD

**Issue by baileyherbert** [Gert-dev/php-integrator-autocomplete-plus#65]
Atom's built-in autocomplete-plus shows realtime suggestions as you type. PHP Integrator's autocomplete waits until you stop typing to show suggestions. Is there any way to enable realtime (as you type) suggestions?

**Comment by Gert-dev** [comment]
There is no such debounce present in this package specifically, everything is managed by autocomplete-plus. However, it is the case that fetching suggestions in this package is much slower than, for example, Atom's built-in fuzzy matching simply because it involves much more work and actual static code analysis. Due to this, I'm afraid this is simply due to slow performance.

I'll keep looking out for ways to improve performance, but I'm afraid the low-hanging fruit (e.g. caching results) have already been plucked for the parsing.
