### ISSUE TITLE
“Reindex Project” doesn’t do anything, no autocompletion at all (regression)

### ISSUE THREAD

**Issue by lxg** [Gert-dev/php-integrator-autocomplete-plus#66]
I’ve recently upgraded to Atom 1.9.9 and have most of the php-integrator-* packages installed. Until recently, PHP autocompletion was working like a charm, but it stopped. (Running Atom 1.9.9 on Linux.)

Unfortunately, I can’t really provide clues or error messages. What I can say is that (forcibly) reindexing doesn’t have any effect. Autocompletion doesn’t work anymore.

I tried starting Atom from the command line with `-f`, but the only error I see whenI trigger the reindexing process is “X error received: serial 22361, error_code 3 (BadWindow (invalid Window parameter)), request_code 3, minor_code 0 (X_GetWindowAttributes)”, but I hardly believe that this has anything to do with the plugin.

I’ll be happy to provide more information, just tell me what you need.

**Comment by Gert-dev** [comment]
Hello. Have you perchance also recently updated to base package 1.2.0? In that case, do you also have project support fully set up (see also the README, the CHANGELOG and [1]).

[1] https://github.com/Gert-dev/php-integrator-base/issues/214

**Comment by lxg** [comment]
Yup, that was the issue. Sorry for bothering.

Anyway, maybe there should be an error message if the dependency is missing? That would avoid invalid bug reports such as this one.

**Comment by Gert-dev** [comment]
No problem. Showing an error message is in fact, harder than it seems as I can't depend on atom-project-manager directly, I can only depend on the service it is providing. Services are injected asynchronously into the package at start-up (and if you deactivate the package, I get a signal that the service is no longer present). This means that when initializing, I can't assume that the service isn't present because it is not set, as it may still be loading.

The best I can do something like register a timeout so that the check happens after a couple of seconds instead of immediately, but that might still not be sufficient on very slow machines. You can, however, use the "Test config" command via the command palette, which will complain if the service isn't set.

**Comment by lxg** [comment]
Ok, thanks for the clarification!
