### ISSUE TITLE
Differences between this project and Peekmo's

### ISSUE THREAD

**Issue by alexandernst** [Gert-dev/php-integrator-autocomplete-plus#7]
Hi, I have been watching closely Peekmo's autocomplete-php project and your contributions to it. How is this project different from Peekmo's? What are the improvements?

Regards

**Comment by Gert-dev** [comment]
Hello

I realize the 'various improvements' mentioned in the README of the base package is somewhat vague. This was mostly due to the fact that at that point there weren't many improvements yet. However, most features from Peekmo's autocomplete-php are included in the various packages.

This project splits all functionality up into several different packages. The intent behind this was primarily separation of concern as well as to allow other developers to plug in to the same service to provide other functionality for PHP that we can all benefit from. The original discussion is located [here](https://github.com/Peekmo/atom-autocomplete-php/issues/158).

The first version released of each package (0.1.0) is mostly the same as Peekmo's package, but the code has been majorly refactored and minor improvements and bug fixes have occurred here and there. However, after that initial release, I've started doing various improvements and adding new features gradually, of which the highlights can already be found in the `CHANGELOG.md` files in the root of each package. This includes things such as:
* An indicator when indexing is failing.
* Navigation to user-defined global constants.
* Autocompletion, tooltips and navigation for user-defined global functions.
* More things happening asynchronously using promises, improving performance.
* ...

If you have any further questions, I'll gladly answer them.

**Comment by alexandernst** [comment]
Nice to know all that. I'll keep watching your repo as well, thank you for the reply!
